### ISSUE TITLE
[Authentication] - Authenticating to the console and to each host is burdensome

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#177]
**Is your feature request related to a problem? Please describe.**
I was really excited for WAC when it came out but it's had the same frustrating problem since beta: constantly entering credentials.

In my humble opinion, WAC violates, through it's UI, an IT security best-practice called RBAC. If I login to Windows with a standard user account I can't manage my workstations or my servers because I use different accounts for both of those levels.

When I click on a server I have to enter alternate credentials and those do not persist to other servers. I have to enter the credentials every time. Which means I have to look them up in LastPass every time.

**Describe the solution you'd like**
At the very least, (1) the console should accept my Windows credentials and not popup a login box and (2) I would like to authenticate only one time to a resource (this doesn't include the initial login to the console) and persist those credentials to other resources. So when I click on one server for the first time, and enter the credentials, I should be able to pass those credentials through to another server instead of seeing the panel asking for credentials again.

Ideally, WAC would securely store credentials at a system level so that I could assign those credentials to individual resources.

**Describe alternatives you've considered**
Not using WAC.

**Comment by RebeccaMbulaMs** [comment]
Hello @cparker4486,  
My name is Rebecca, Product Manager on WAC team.
Are you experiencing this issue on the latest version of WAC (https://aka.ms/wacdownload)?
We fixed a few issues with RBAC on our .2 release.
Kind regards!

**Comment by cparker4486** [comment]
Hi @RebeccaMbulaMs .

I'm on 2110.2 but, yes, this issue remains.

I tried again yesterday to administer a Windows 10 PC and ran into another scenario to share. I was popping out the Events window a few times and each time had to type in credentials. I even chose the option "Use these credentials for all connections." but I was still asked to put in credentials when I reopened Events and also when I popped out the PowerShell control.

Thank you.

**Comment by RebeccaMbulaMs** [comment]
Hey @cparker4486, 

I'm sure this is very frustrating for you and I'm sorry that you are experiencing this issue. I believe this is not expected behavior in WAC. Please allow me to consult with my team and get back to you on this.

Kind regards!
